config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root 'sessions#dashboard'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/users', to: 'users#new', as: 'signup'
  post '/magic', to: 'sessions#magic'
  get '/magic', to: 'sessions#magic'
  get '/login/magic_link', to: 'sessions#magic_link_login', as: :magic_link_login
  get 'auth/:provider/callback', to: 'sessions#omniauth'
  resources :leaderboard, only: %i[index]
  resources :exam_performances, only: [:show]
  resources :registrations, only: %i[index new]
  resources :subjects, only: [:show]
  resources :departments, only: [:show]
  resources :users, except: %i[index destroy]

  resources :magic_link_authentication, only: [:create] do
    member do
      post 'create', to: 'magic_link_authentication#create'
    end
  end

  resources :exams, only: [:show] do
    get 'demo_exam', on: :member
    resources :registrations, only: %i[new create]
    post 'submit_exam', on: :member

    member do
      get 'conduct'
    end
  end

  scope '/exam_performances/:id' do
    get 'generate_report', to: 'exam_performances#generate_report', as: 'generate_report'
  end

  namespace :admin do
    root 'admin#index'
    resources :departments, except: [:show]
    resources :subjects, except: [:show]
    resources :exams
    resources :questions, except: [:show]
    resources :users, except: [:show]
    resources :professors, except: [:show]
  end

  match '*unmatched', to: 'application#not_found_method', via: :all, constraints: lambda { |req|
    !req.path.match(%r{\A/rails/active_storage/})
  }
end
# rubocop:enable Metrics/BlockLength

app/models/exam.rb
# frozen_string_literal: true

# This is a class representing an model
class Exam < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :subject
  has_many :registrations, dependent: :destroy
  has_many :users, through: :registrations
  has_many :questions, dependent: :destroy
  has_many :exam_performances, dependent: :destroy

  validates :exam_name, presence: true, length: { minimum: 3, message: 'must contain at least 3 letters' }
  validates :subject_id, presence: { message: 'Please select subject' }
  validate :start_time_must_be_future, on: :create
  validates :start_time, presence: { message: 'Time cannot be blank' }
  validates :duration, presence: true, numericality: { greater_than: 0, message: 'must be greater than zero' }

  def start_time_must_be_future
    return unless start_time.present? && start_time <= DateTime.now

    errors.add(:start_time, 'must be in the future')
  end

  def end_time
    start_time + duration.minutes
  end

  def shuffled_questions
    questions.to_a.shuffle
  end

  def calculate_score(user_answers)
    total_questions = questions.count
    score = 0
    unless user_answers.nil?
      questions.each_with_index do |question, index|
        user_answer = user_answers[index.to_s].to_i
        correct_answer = question.correct_answer

        score += 1 if user_answer == correct_answer
      end
    end

    (score.to_f / total_questions) * 100
  end

  def create_exam_performance(user_id, marks_obtained)
    ExamPerformance.create(exam: self, user_id:, marks_obtained:)
  end

  def demo_exam
    Exam.find_by(subject_id:, is_demo: true)
  end

  index_name "exams_#{Rails.env}"

  settings do
    mappings dynamic: 'false' do
      indexes :exam_name, type: 'text'
      indexes :start_time, type: 'date'
      indexes :duration, type: 'integer'
    end
  end

  # rubocop:disable Metrics/MethodLength
  def self.search_by_exam_name(search_term)
    search_definition = {
      size: 20,
      query: {
        match_phrase_prefix: {
          exam_name: {
            query: search_term.downcase
          }
        }
      }
    }
    __elasticsearch__.search(search_definition).records
  end
  # rubocop:enable Metrics/MethodLength

  def self.filter_by_department(department)
    search_definition = {
      query: {
        bool: {
          filter: {
            term: { "subject.department.department_name.keyword": department }
          }
        }
      }
    }
    __elasticsearch__.search(search_definition).records
  end

  def self.filter_by_subject(subject)
    search_definition = {
      query: {
        bool: {
          filter: {
            term: { "subject.subject_name.keyword": subject }
          }
        }
      }
    }
    __elasticsearch__.search(search_definition).records
  end
end

app/controllers/admin/exams_controller.rb
# frozen_string_literal: true

module Admin
  # class Admin::Admin::DepartmentsController
  class ExamsController < ApplicationController
    include RegistrationsHelper

    before_action :authenticate_admin
    before_action :find_exam, only: %i[show edit update destroy]
    before_action :load_subjects, only: %i[new create edit update]

    def index
      @exams = filter_and_sort_exams(Exam.all, params).page(params[:page]).per(12)
    end

    def show; end

    def edit; end

    def update
      if @exam.update(exam_params)
        flash[:success] = 'Exam was successfully updated.'
        redirect_to admin_exams_path
      else
        render :edit
      end
    end

    def new
      @exam = Exam.new
    end

    def create
      @exam = Exam.new(exam_params)
      if @exam.save
        flash[:success] = 'Exam was successfully created.'
        redirect_to admin_exams_path
      else
        render :new
      end
    end

    def destroy
      @exam.destroy
      flash[:danger] = 'Exam was successfully destroyed.'
      redirect_to admin_exams_path
    end

    private

    def exam_params
      params.require(:exam).permit(:exam_name, :duration, :subject_id, :is_demo, :start_time)
    end

    def find_exam
      @exam = Exam.find(params[:id])
    end

    def load_subjects
      @subjects = Subject.all
    end
  end
end

app/controllers/exams_controller.rb
# frozen_string_literal: true

# This is a class representing an controller
class ExamsController < ApplicationController
  before_action :find_exam, only: %i[conduct demo_exam show submit_exam]
  before_action :require_user

  def conduct
    current_user.mark_exam_in_progress(@exam)
  end

  def demo_exam; end

  def show; end

  def submit_exam
    user_answers = params[:user_answers]
    redirect_to_exam_performance(user_answers)
    current_user.clear_exam_in_progress(@exam)
  end

  private

  def find_exam
    @exam = Exam.find(params[:id])
  end

  def handle_no_user_answers
    flash[:danger] = 'Please select answers for all questions.'
    redirect_to conduct_exam_path(exam_id: @exam.id)
  end

  def redirect_to_exam_performance(user_answers)
    percentage_score = @exam.calculate_score(user_answers)
    exam_performance = @exam.create_exam_performance(current_user.id, percentage_score)
    redirect_to exam_performance_path(exam_performance)
  end
end

app/helpers/exams_helper.rb
# frozen_string_literal: true

# This is a class representing an helper
module ExamsHelper
  def count_questions(exam)
    exam.questions.count
  end
end

app/views/admin/exams/_form.html.erb
<%= form_with(model: @exam, url: url, class: 'form', method: method) do |form| %>
  <div class="form-group">
    <%= form.label :exam_name, class: 'required' %>
    <%= form.text_field :exam_name, class: 'form-control ' %>
    <% if form.object.errors.has_key?(:exam_name) %>
      <span class="error text-danger">
        <%= form.object.errors[:exam_name].first %>
      </span>
    <% end %>
  </div>

  <div class="form-group ">
    <%= form.label :subject_id, 'Subject', class:'required' %>
    <%= form.collection_select :subject_id, @subjects, :id, :subject_name, prompt: 'Select a subject', class: 'form-control' %>
    <% if form.object.errors.has_key?(:subject_id) %>
      <span class="error text-danger">
        <%= form.object.errors[:subject_id].first %>
      </span>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :start_time, 'Exam Date and Time', class:'required' %>
    <%= form.datetime_local_field :start_time, class: 'form-control' %>
    <% if form.object.errors.has_key?(:start_time) %>
      <span class="error text-danger" >
        <%= form.object.errors[:start_time].first %>
      </span>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :duration, class:'required' %>
    <%= form.number_field :duration, class: 'form-control' %>
    <% if form.object.errors.has_key?(:duration) %>
      <span class="error text-danger">
        <%= form.object.errors[:duration].first %>
      </span>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :is_demo, 'Exam Type' %>
    <%= form.select :is_demo, options_for_select([['Demo Exam', true], ['Actual Exam', false]], @exam.is_demo?), {}, class: 'form-control' %>
    <% if form.object.errors.has_key?(:is_demo) %>
      <span class="error text-danger">
        <%= form.object.errors[:is_demo].first %>
      </span>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit submit_button_text, class: 'btn btn-primary' %>
    <%= link_to 'Cancel', admin_exams_path, class: 'btn btn-secondary'%>
  </div>
<% end %>

app/views/admin/exams/edit.html.erb
<div class='container'>
  <h1>Edit Exam</h1>
  <div class="bg-light">
  <%= render 'form', url: admin_exam_path(@exam), method: 'patch', submit_button_text: 'Update Exam' %>
  </div>
</div>

app/views/admin/exams/index.html.erb
<div class='container'>
  <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand float-left" href="#">Manage Exams</a>
    <%= link_to "Home", admin_root_path, class: "btn btn-outline-primary" %>
  </nav>

  <div class="mt-3 d-flex justify-content-between">
    <%= link_to 'Add Exam', new_admin_exam_path, class: 'btn btn-primary' %>
  
    <div class="">
      <div class="mx-2 ">
        <%= form_tag admin_exams_path, method: :get, class: "form-inline" do %>
          <%= text_field_tag :search, params[:search], class: "form-control ", placeholder: "Search exams..." %>
          <%= select_tag :department, options_from_collection_for_select(Department.all, :department_name, :department_name, params[:department]), include_blank: "All Departments", class: "form-control m-1" %>
          <%= select_tag :subject, options_from_collection_for_select(subject_options(params[:department]), :subject_name, :subject_name, params[:subject]), include_blank: "All Subjects", class: "form-control m-1" %>
          <%= submit_tag "Search", class: "btn btn-outline-primary m-1" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <% @exams.each do |exam| %>
      <div class="col-md-4 mt-5">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= exam.exam_name %></h5>
            <% if exam.is_demo %>
              <span class="badge badge-primary float-right">Demo</span>
            <% else %>
              <span class="badge badge-secondary float-right">Actual</span>
            <% end %>
            <p class="card-text">Exam Date: <%= (exam.start_time).strftime('%m/%d/%Y') %></p>
            <p class="card-text">Exam Time: <%= (exam.start_time).strftime('%H:%M %p') %></p>
            <p class="card-text">Exam Duration: <%= exam.duration %></p>
            <p class="card-text">Total Questions: <%= count_questions(exam) %></p>
          </div>
          <div class="card-footer">
            <a href="<%= admin_exam_path(exam) %>" class="btn btn-primary">View Details</a>
            <a href="<%= edit_admin_exam_path(exam) %>" class="btn btn-secondary">Edit</a>
            <a href="<%= admin_exam_path(exam) %>" class="btn btn-danger" data-confirm="Are you sure?" data-method="delete" rel="nofollow">Delete</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>


  <ul class="pagination justify-content-center mt-4">
    <% if @exams.current_page > 1 %>
      <li class="page-item">
        <%= link_to '&laquo; Previous'.html_safe, { page: @exams.current_page - 1 }, class: 'page-link' %>
      </li>
    <% end %>

    <% (1..@exams.total_pages).each do |page| %>
      <% if page == @exams.current_page %>
        <li class="page-item active">
          <span class="page-link">
            <%= page %>
            <span class="visually-hidden">(current)</span>
          </span>
        </li>
      <% else %>
        <li class="page-item">
          <%= link_to page, { page: page }, class: 'page-link' %>
        </li>
      <% end %>
    <% end %>

    <% if @exams.current_page < @exams.total_pages %>
      <li class="page-item">
        <%= link_to 'Next &raquo;'.html_safe, { page: @exams.current_page + 1 }, class: 'page-link' %>
      </li>
    <% end %>
  </ul>
</div>

app/views/admin/exams/new.html.erb
<div class='container'>
  <h1>Create New Exam</h1>
  <div class="bg-light">
  <%= render 'form', url: admin_exams_path, method: 'post', submit_button_text: 'Create Exam' %>
  </div>
</div>

app/views/admin/exams/show.html.erb
<div class='container'>
  <h1>Exam Details</h1>

  <div class="card">
    <div class="card-header">
      <h5 class="card-title"><%= @exam.exam_name %></h5>
    </div>
    <div class="card-body">
      <p class="card-text">Exam Date: <%= (@exam.start_time).strftime('%m/%d/%Y %H:%M %p') %></p>
      <p class="card-text">Total Questions: <%= count_questions(@exam) %></p>
      <p class="card-text">Exam Duration: <%= @exam.duration %></p>
    </div>
    <div class="card-footer">
      <%= link_to 'Edit', edit_admin_exam_path(@exam), class: 'btn btn-primary' %>
      <%= link_to 'Cancel', admin_exams_path, class: 'btn btn-secondary' %>
      <%= link_to 'Delete', admin_exam_path(@exam), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </div>
  </div>
</div>