config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root 'sessions#dashboard'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/users', to: 'users#new', as: 'signup'
  post '/magic', to: 'sessions#magic'
  get '/magic', to: 'sessions#magic'
  get '/login/magic_link', to: 'sessions#magic_link_login', as: :magic_link_login
  get 'auth/:provider/callback', to: 'sessions#omniauth'
  resources :leaderboard, only: %i[index]
  resources :exam_performances, only: [:show]
  resources :registrations, only: %i[index new]
  resources :subjects, only: [:show]
  resources :departments, only: [:show]
  resources :users, except: %i[index destroy]

  resources :magic_link_authentication, only: [:create] do
    member do
      post 'create', to: 'magic_link_authentication#create'
    end
  end

  resources :exams, only: [:show] do
    get 'demo_exam', on: :member
    resources :registrations, only: %i[new create]
    post 'submit_exam', on: :member

    member do
      get 'conduct'
    end
  end

  scope '/exam_performances/:id' do
    get 'generate_report', to: 'exam_performances#generate_report', as: 'generate_report'
  end

  namespace :admin do
    root 'admin#index'
    resources :departments, except: [:show]
    resources :subjects, except: [:show]
    resources :exams
    resources :questions, except: [:show]
    resources :users, except: [:show]
    resources :professors, except: [:show]
  end

  match '*unmatched', to: 'application#not_found_method', via: :all, constraints: lambda { |req|
    !req.path.match(%r{\A/rails/active_storage/})
  }
end
# rubocop:enable Metrics/BlockLength

app/controllers/leaderboard_controller.rb
# frozen_string_literal: true

# This is a class representing an controller
class LeaderboardController < ApplicationController
  before_action :require_user

  def index
    @performances_summary = ExamPerformance.performances_summary(current_user)
    exam_averages_array = @performances_summary[:exam_averages].to_a
    @exam_averages = Kaminari.paginate_array(exam_averages_array).page(params[:page]).per(5)
  end
end

app/views/leaderboard/index.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-toggler h4 text-dark" href="#">Leader Board</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Dash Board", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Registrations", registrations_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Leader Board", leaderboard_index_path(@user), class: "nav-link h5 text-dark" %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="userDropdown">
          <%= link_to "Profile", user_path(@current_user), class: "dropdown-item" %>
          <a href="logout" class="dropdown-item">Log Out</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

  
  <div class="row mt-4">
    <div class="col-md-6">
      <div class="card bg-light">
        <div class="card-body">
          <h2 class="card-title">Your Rank</h2>
          <div class="row">
            <div class="col">
              <% if @current_user.college.present? %>
                <% if ExamPerformance.college_rank(@current_user) %>
                  <p class="card-text">College Rank: <%= ExamPerformance.college_rank(@current_user) + 1 %></p>
                <% end %>
              <% else %>
                <p class="card-text">Update your profile to get college-wise rank</p>
              <% end %>
            </div>
            <div class="col">
              <% if ExamPerformance.overall_rank(@current_user) %>
                <p class="card-text">Overall Rank: <%= ExamPerformance.overall_rank(@current_user) + 1 %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-md-6">
      <h2>Your Department-wise Performance</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Department</th>
            <th>Average Score</th>
          </tr>
        </thead>
        <tbody>
          <% @performances_summary[:department_performance].each do |department, average_score| %>
            <tr>
              <td><%= department%></td>
              <td><%= average_score %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-6">
      <h2>Your Department-wise Performance Chart</h2>
      <%= pie_chart @performances_summary[:department_performance] %>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-md-6">
      <h2>Your Subject-wise Performance</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Subject</th>
            <th>Average Score</th>
          </tr>
        </thead>
        <tbody>
          <% @performances_summary[:subject_performance].each do |subject, average_score| %>
            <tr>
              <td><%=subject%></td>
              <td><%= average_score %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-6">
      <h2>Your Subject-wise Performance Chart</h2>
      <%= pie_chart @performances_summary[:subject_performance] %>
    </div>
  </div>

<div class="row mt-5 overflow-auto">
  <div class="col-md-6">
    <h2>Your Exam-wise Performance</h2>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Exam</th>
          <th>Your Marks</th>
          <th>Average Marks</th>
          <th>Highest Marks</th>
          <th>Generate Report</th>
          <th>Chart</th>
        </tr>
      </thead>
      <tbody>
        <% @exam_averages.each do |exam_id, average_marks| %>
          <% exam = Exam.find_by(id: exam_id) %>
          <% performance = @performances_summary[:exam_performances].find_by(exam_id: exam_id, user_id: @current_user) %>
          <% highest_marks = @performances_summary[:highest_marks][exam_id] %>
          <% user_performance = @performances_summary[:exam_performances].find_by(exam_id: exam_id, user_id: @current_user.id) %>
          <tr>
            <td><%= exam ? exam.exam_name : 'Exam not found' %></td>
            <td><%= user_performance ? user_performance.marks_obtained : 'N/A' %></td>
            <td><%= average_marks %></td>
            <td><%= highest_marks %></td>
            <td><%= link_to "Generate Performance Report", generate_report_path(performance.id), class: "" if performance %></td>
            <td>
              <% if exam && user_performance %>
                <%= column_chart [
                  ['Your Mark', user_performance.marks_obtained],
                  ['Average Mark', average_marks],
                  ['Highest Mark', highest_marks]
                ], library: { responsive: true } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>

 <ul class="pagination justify-content-center">
    <% if  @exam_averages.current_page > 1 %>
      <li class="page-item">
        <%= link_to '&laquo; Previous'.html_safe, { page:  @exam_averages.current_page - 1 }, class: 'page-link' %>
      </li>
    <% end %>

    <% (1.. @exam_averages.total_pages).each do |page| %>
      <% if page ==  @exam_averages.current_page %>
        <li class="page-item active">
          <span class="page-link">
            <%= page %>
            <span class="visually-hidden">(current)</span>
          </span>
        </li>
      <% else %>
        <li class="page-item">
          <%= link_to page, { page: page }, class: 'page-link' %>
        </li>
      <% end %>
    <% end %>

    <% if  @exam_averages.current_page <  @exam_averages.total_pages %>
      <li class="page-item">
        <%= link_to 'Next &raquo;'.html_safe, { page:  @exam_averages.current_page + 1 }, class: 'page-link' %>
      </li>
    <% end %>
  </ul>

</div>