config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root 'sessions#dashboard'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/users', to: 'users#new', as: 'signup'
  post '/magic', to: 'sessions#magic'
  get '/magic', to: 'sessions#magic'
  get '/login/magic_link', to: 'sessions#magic_link_login', as: :magic_link_login
  get 'auth/:provider/callback', to: 'sessions#omniauth'
  resources :leaderboard, only: %i[index]
  resources :exam_performances, only: [:show]
  resources :registrations, only: %i[index new]
  resources :subjects, only: [:show]
  resources :departments, only: [:show]
  resources :users, except: %i[index destroy]

  resources :magic_link_authentication, only: [:create] do
    member do
      post 'create', to: 'magic_link_authentication#create'
    end
  end

  resources :exams, only: [:show] do
    get 'demo_exam', on: :member
    resources :registrations, only: %i[new create]
    post 'submit_exam', on: :member

    member do
      get 'conduct'
    end
  end

  scope '/exam_performances/:id' do
    get 'generate_report', to: 'exam_performances#generate_report', as: 'generate_report'
  end

  namespace :admin do
    root 'admin#index'
    resources :departments, except: [:show]
    resources :subjects, except: [:show]
    resources :exams
    resources :questions, except: [:show]
    resources :users, except: [:show]
    resources :professors, except: [:show]
  end

  match '*unmatched', to: 'application#not_found_method', via: :all, constraints: lambda { |req|
    !req.path.match(%r{\A/rails/active_storage/})
  }
end
# rubocop:enable Metrics/BlockLength

app/models/department.rb
# frozen_string_literal: true

# This is a class representing an model
class Department < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_many :subjects, dependent: :destroy
  has_many :exams, through: :subjects
  has_many :professors, dependent: :destroy

  validates :department_name, presence: true, length: { minimum: 3, message: 'must contain at least 3 letters' }

  scope :filtered_departments, lambda { |params|
    if params[:q].present?
      search_departments(params[:q])
    else
      all_departments
    end.page(params[:page]).per(params[:per_page])
  }

  scope :search_departments, lambda { |query|
    search(query).records
  }

  scope :all_departments, lambda {
    all
  }
end

app/controllers/admin/departments_controller.rb
# frozen_string_literal: true

module Admin
  # class Admin::Admin::DepartmentsController
  class DepartmentsController < Admin::AdminController
    before_action :authenticate_admin
    before_action :find_department, only: %i[edit update destroy]

    def index
      @departments = Department.filtered_departments(params)
    end

    def new
      @department = Department.new
    end

    def create
      @department = Department.new(department_params)
      if @department.save
        flash[:success] = 'Department created successfully.'
        redirect_to admin_departments_path
      else
        render :new
      end
    end

    def destroy
      return unless @department.destroy

      flash[:danger] = 'Department was successfully destroyed.'
      redirect_to admin_departments_path
    end

    def edit; end

    def update
      if @department.update(department_params)
        flash[:success] = 'Department was successfully updated.'
        redirect_to admin_departments_path
      else
        render :edit
      end
    end

    private

    def department_params
      params.require(:department).permit(:department_name)
    end

    def find_department
      @department = Department.find(params[:id])
    end
  end
end

app/controllers/departments_controller.rb
# frozen_string_literal: true

# This is a class representing an controller
class DepartmentsController < ApplicationController
  before_action :require_user

  def show
    @department = Department.find(params[:id])
  end
end

app/views/admin/departments/_form.html.erb
<div class="form-group">
  <%= f.label :department_name, class:'required' %>
  <%= f.text_field :department_name, class: 'form-control' %>
  <% if @department.errors.has_key?(:department_name) %>
    <span class="error text-danger">
      <%= @department.errors[:department_name].first %>
    </span>
  <% end %>
</div>
<%= f.submit class: 'btn btn-primary' %>
<%= link_to 'Cancel', admin_departments_path, class: 'btn btn-secondary' %>

app/views/admin/departments/edit.html.erb
<div class='container'>
  <h1>Edit Department</h1>
  <%= form_for(@department, url: admin_department_path(@department), method: :patch) do |f| %>
    <%= render 'form', f: f %>
  <% end %>
</div>

app/views/admin/departments/index.html.erb
<div class='container'>
  <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand float-left" href="#">Manage Departments</a>
    <%= link_to "Home", admin_root_path, class: "btn btn-outline-primary" %>
  </nav>

  <div class="mb-3 mt-4 d-flex justify-content-between p-2">
    <%= link_to "New Department", new_admin_department_path, class: "btn btn-primary mr-5" %>

    <%= form_tag admin_departments_path, method: :get, class: "col-5 mr-" do %>
      <div class="input-group ">
        <%= text_field_tag :q, params[:q], class: "form-control ", placeholder: "Search Departments..." %>
        <div class="input-group-append">
          <%= submit_tag "Search", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>


  <div class="table-responsive">
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @departments.each do |department| %>
          <tr>
            <td><%= department.id %></td>
            <td><%= department.department_name %></td>
            <td>
              <%= link_to 'Edit', edit_admin_department_path(department), class: 'btn btn-secondary' %>
              <%= link_to 'Delete', admin_department_path(department), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <ul class="pagination justify-content-center">
      <% if @departments.current_page > 1 %>
        <li class="page-item">
          <%= link_to '&laquo; Previous'.html_safe, { page: @departments.current_page - 1 }, class: 'page-link' %>
        </li>
      <% end %>

      <% (1..@departments.total_pages).each do |page| %>
        <% if page == @departments.current_page %>
          <li class="page-item active">
            <span class="page-link">
              <%= page %>
              <span class="visually-hidden">(current)</span>
            </span>
          </li>
        <% else %>
          <li class="page-item">
            <%= link_to page, { page: page }, class: 'page-link' %>
          </li>
        <% end %>
      <% end %>

      <% if @departments.current_page < @departments.total_pages %>
        <li class="page-item">
          <%= link_to 'Next &raquo;'.html_safe, { page: @departments.current_page + 1 }, class: 'page-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/admin/departments/new.html.erb
<div class='container'>
  <h1>Create New Department</h1>
  <%= form_for [:admin, @department] do |f| %>
    <%= render 'form', f: f %>
  <% end %>
</div>