config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  root 'sessions#dashboard'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/users', to: 'users#new', as: 'signup'
  post '/magic', to: 'sessions#magic'
  get '/magic', to: 'sessions#magic'
  get '/login/magic_link', to: 'sessions#magic_link_login', as: :magic_link_login
  get 'auth/:provider/callback', to: 'sessions#omniauth'
  resources :leaderboard, only: %i[index]
  resources :exam_performances, only: [:show]
  resources :registrations, only: %i[index new]
  resources :subjects, only: [:show]
  resources :departments, only: [:show]
  resources :users, except: %i[index destroy]

  resources :magic_link_authentication, only: [:create] do
    member do
      post 'create', to: 'magic_link_authentication#create'
    end
  end

  resources :exams, only: [:show] do
    get 'demo_exam', on: :member
    resources :registrations, only: %i[new create]
    post 'submit_exam', on: :member

    member do
      get 'conduct'
    end
  end

  scope '/exam_performances/:id' do
    get 'generate_report', to: 'exam_performances#generate_report', as: 'generate_report'
  end

  namespace :admin do
    root 'admin#index'
    resources :departments, except: [:show]
    resources :subjects, except: [:show]
    resources :exams
    resources :questions, except: [:show]
    resources :users, except: [:show]
    resources :professors, except: [:show]
  end

  match '*unmatched', to: 'application#not_found_method', via: :all, constraints: lambda { |req|
    !req.path.match(%r{\A/rails/active_storage/})
  }
end
# rubocop:enable Metrics/BlockLength

app/views/admin/admin/index.html.erb
<div class="container mt-1">
  <nav class="navbar navbar-light bg-light mb-5">
    <a class="navbar-brand float-left" href="#">Admin Dashboard</a>
    <%= link_to "Log Out", logout_path, class: "btn btn-outline-primary" %>
  </nav>

  <div class="row">
    <div class="col-md-6">
      <div class="card mb-4">
        <div class="card-header bg-primary text-white">
          <h2>Manage Departments</h2>
        </div>
        <div class="card-body">
          <p class="card-text">Here you can create, edit, and delete departments.</p>
          <a href="<%= admin_departments_path %>" class="btn btn-primary">Manage Departments</a>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card mb-4">
        <div class="card-header bg-primary text-white">
          <h2>Manage Subjects</h2>
        </div>
        <div class="card-body">
          <p class="card-text">Here you can create, edit, and delete subjects.</p>
          <a href="<%= admin_subjects_path %>" class="btn btn-primary">Manage Subjects</a>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card mb-4">
        <div class="card-header bg-primary text-white">
          <h2>Manage Exams</h2>
        </div>
        <div class="card-body">
          <p class="card-text">Here you can create, edit, and delete exams.</p>
          <a href="<%= admin_exams_path %>" class="btn btn-primary">Manage Exams</a>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card mb-4">
        <div class="card-header bg-primary text-white">
          <h2>Manage Questions</h2>
        </div>
        <div class="card-body">
          <p class="card-text">Here you can create, edit, and delete questions.</p>
          <a href="<%= admin_questions_path %>" class="btn btn-primary">Manage Questions</a>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card mb-4">
        <div class="card-header bg-primary text-white">
          <h2>Manage users</h2>
        </div>
        <div class="card-body">
          <p class="card-text">Here you can create, edit, and delete admins and see all the users along their registered exams.</p>
          <a href="<%= admin_users_path %>" class="btn btn-primary">Manage Users</a>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card mb-4">
        <div class="card-header bg-primary text-white">
          <h2>Manage professors</h2>
        </div>
        <div class="card-body">
          <p class="card-text">Here you can create, edit, and delete admins and see all the users along their registered exams.</p>
          <a href="<%= admin_professors_path %>" class="btn btn-primary">Manage Users</a>
        </div>
      </div>
    </div>
  </div>
</div>